name: Build and Push Apptainer Container


on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0

      - name: Determine Version/Tag
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            RAW_VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${RAW_VERSION#v}
          else
            VERSION="0.0.0+$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          echo "LOWER_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Build Apptainer Container
        run: |
          sudo apptainer build \
            --build-arg VERSION=${{ env.VERSION }} \
            env.sif containers/env.def
          
          sudo chown $USER env.sif

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | apptainer registry login -u ${{ github.actor }} --password-stdin oras://${{ env.REGISTRY }}


      - name: Push Container to GHCR
        run: |
          apptainer push env.sif oras://${{ env.REGISTRY }}/${{ env.LOWER_REPO }}-sif:${{ env.VERSION }}
          
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            apptainer push env.sif oras://${{ env.REGISTRY }}/${{ env.LOWER_REPO }}-sif:latest
          fi